
name: deploy-solution-to-prod

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  deploy-solution:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Power Platform CLI (PAC)
        shell: pwsh
        run: |
          # Install PAC via .NET tool (reliable, no huge action zipball download)
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool
          pac --version

      - name: Pack managed solution
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "out\release\Managed" | Out-Null

          pac solution pack
            --folder "src\solutions\Unmanaged\GitHubActionsDevOpsDemo" `
            --zipfile "out\release\Managed\GitHubActionsDevOpsDemo.zip" `
            --packagetype Managed

          if (!(Test-Path "out\release\Managed\GitHubActionsDevOpsDemo.zip")) {
            throw "Pack output not found."
          }
          
          - name: Import solution to PROD
           shell: pwsh
           env:
           ENV_URL: "https://powerplatcoe-old.crm.dynamics.com/"
           TENANT_ID: "db05faca-c82a-4b9d-b9c5-0f64b6755421"
           APP_ID: "4fec5240-fd45-408b-8276-d60c97798c49"
